# Generated by Django 4.1.7 on 2024-06-30 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('status', models.CharField(default='pending', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('pic', models.ImageField(blank=True, default=None, null=True, upload_to='sports/')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inning', models.CharField(default='1', max_length=2)),
                ('total_score', models.IntegerField(default=0)),
                ('over', models.IntegerField(default=0)),
                ('current_over', models.DecimalField(db_index=True, decimal_places=1, default=0, max_digits=3)),
                ('status', models.CharField(default='not started', max_length=15)),
                ('win_loss', models.CharField(blank=True, default='', max_length=5, null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportsapp.match')),
            ],
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportsapp.sport')),
            ],
        ),
        migrations.CreateModel(
            name='TeamPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportsapp.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportsapp.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportsapp.team')),
            ],
        ),
        migrations.CreateModel(
            name='ScoreAdd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ball', models.IntegerField(default=0)),
                ('run', models.IntegerField(default=0)),
                ('comment', models.CharField(default='', max_length=10)),
                ('score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportsapp.score')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportsapp.team'),
        ),
    ]
